### ISSUE TITLE
[FIX] Low color contrast

### ISSUE THREAD

**Issue by vikasganiga05** [coding-in-public/password-generator#1] opened 2022-03-02 19:32 UTC
The text inside the container is not clearly visible. The background image has light colors in it. So, increase the background color opacity to 0.75 to see the text clearly.

Replace classname `bg-zinc-800/30` on `<main>` tag to `bg-zinc-800/75` in `src/index.html` file.

### Screenshots
>Before :point_down: 

![image](https://user-images.githubusercontent.com/74750414/156435183-062a539d-5d81-4cc2-ae35-ec918c9f298f.png)

>After :point_down: 

![image](https://user-images.githubusercontent.com/74750414/156435253-284d7286-a3d6-408b-a112-47d570aa78e6.png)

**Comment by coding-in-public** [comment] 2022-03-02 22:51
Fixed on community improvements branch. Thanks!

**Closed as completed by coding-in-public** 2022-03-02 22:51 UTC

**Comment by vikasganiga05** [comment] 2022-03-03 01:38
> Fixed on community improvements branch. Thanks!

It's my pleasure :pray:

**Comment by coding-in-public** [comment] 2022-03-04 16:54
Yeah, the problem is that I don't think Firefox treats the filter:blur() the same way, so that's the reason for the low contrast. But it's probably best to just change it so it looks good on all browsers. Thanks again!

**Comment by vikasganiga05** [comment] 2022-03-16 00:58
> Yeah, the problem is that I don't think Firefox treats the filter:blur() the same way, so that's the reason for the low contrast. But it's probably best to just change it so it looks good on all browsers. Thanks again!

Most welcome!
